//! Generated by `cargo run --example norm_gen` — do not hand-edit rows.
use app_lib::xref::normalize_plugin_name;

#[test]
fn norm_gen_00000() {
    assert_eq!(normalize_plugin_name(""), "");
}

#[test]
fn norm_gen_00001() {
    assert_eq!(normalize_plugin_name("   "), "");
}

#[test]
fn norm_gen_00002() {
    assert_eq!(normalize_plugin_name("  spaced  name  "), "spaced name");
}

#[test]
fn norm_gen_00003() {
    assert_eq!(normalize_plugin_name("(VST3)"), "(vst3)");
}

#[test]
fn norm_gen_00004() {
    assert_eq!(normalize_plugin_name("(x64)"), "(x64)");
}

#[test]
fn norm_gen_00005() {
    assert_eq!(normalize_plugin_name("Compressor"), "compressor");
}

#[test]
fn norm_gen_00006() {
    assert_eq!(normalize_plugin_name("Compressor (AAX)"), "compressor");
}

#[test]
fn norm_gen_00007() {
    assert_eq!(normalize_plugin_name("Compressor (ARM64)"), "compressor");
}

#[test]
fn norm_gen_00008() {
    assert_eq!(normalize_plugin_name("Compressor (AU)"), "compressor");
}

#[test]
fn norm_gen_00009() {
    assert_eq!(normalize_plugin_name("Compressor (Apple Silicon)"), "compressor");
}

#[test]
fn norm_gen_00010() {
    assert_eq!(normalize_plugin_name("Compressor (Intel)"), "compressor");
}

#[test]
fn norm_gen_00011() {
    assert_eq!(normalize_plugin_name("Compressor (Mono)"), "compressor");
}

#[test]
fn norm_gen_00012() {
    assert_eq!(normalize_plugin_name("Compressor (Stereo)"), "compressor");
}

#[test]
fn norm_gen_00013() {
    assert_eq!(normalize_plugin_name("Compressor (Universal)"), "compressor");
}

#[test]
fn norm_gen_00014() {
    assert_eq!(normalize_plugin_name("Compressor (VST3)"), "compressor");
}

#[test]
fn norm_gen_00015() {
    assert_eq!(normalize_plugin_name("Compressor (x64)"), "compressor");
}

#[test]
fn norm_gen_00016() {
    assert_eq!(normalize_plugin_name("Compressor 32bit"), "compressor");
}

#[test]
fn norm_gen_00017() {
    assert_eq!(normalize_plugin_name("Compressor 64bit"), "compressor");
}

#[test]
fn norm_gen_00018() {
    assert_eq!(normalize_plugin_name("Compressor [x64]"), "compressor");
}

#[test]
fn norm_gen_00019() {
    assert_eq!(normalize_plugin_name("Compressor x64"), "compressor");
}

#[test]
fn norm_gen_00020() {
    assert_eq!(normalize_plugin_name("Compressor x86"), "compressor");
}

#[test]
fn norm_gen_00021() {
    assert_eq!(normalize_plugin_name("Compressor x86_64"), "compressor");
}

#[test]
fn norm_gen_00022() {
    assert_eq!(normalize_plugin_name("Diva"), "diva");
}

#[test]
fn norm_gen_00023() {
    assert_eq!(normalize_plugin_name("Diva (AAX)"), "diva");
}

#[test]
fn norm_gen_00024() {
    assert_eq!(normalize_plugin_name("Diva (ARM64)"), "diva");
}

#[test]
fn norm_gen_00025() {
    assert_eq!(normalize_plugin_name("Diva (AU)"), "diva");
}

#[test]
fn norm_gen_00026() {
    assert_eq!(normalize_plugin_name("Diva (Apple Silicon)"), "diva");
}

#[test]
fn norm_gen_00027() {
    assert_eq!(normalize_plugin_name("Diva (Intel)"), "diva");
}

#[test]
fn norm_gen_00028() {
    assert_eq!(normalize_plugin_name("Diva (Mono)"), "diva");
}

#[test]
fn norm_gen_00029() {
    assert_eq!(normalize_plugin_name("Diva (Stereo)"), "diva");
}

#[test]
fn norm_gen_00030() {
    assert_eq!(normalize_plugin_name("Diva (Stereo) (x64)"), "diva");
}

#[test]
fn norm_gen_00031() {
    assert_eq!(normalize_plugin_name("Diva (Universal)"), "diva");
}

#[test]
fn norm_gen_00032() {
    assert_eq!(normalize_plugin_name("Diva (VST3)"), "diva");
}

#[test]
fn norm_gen_00033() {
    assert_eq!(normalize_plugin_name("Diva (x64)"), "diva");
}

#[test]
fn norm_gen_00034() {
    assert_eq!(normalize_plugin_name("Diva (x64) (VST3)"), "diva");
}

#[test]
fn norm_gen_00035() {
    assert_eq!(normalize_plugin_name("Diva 32bit"), "diva");
}

#[test]
fn norm_gen_00036() {
    assert_eq!(normalize_plugin_name("Diva 64bit"), "diva");
}

#[test]
fn norm_gen_00037() {
    assert_eq!(normalize_plugin_name("Diva [AU] (x64)"), "diva");
}

#[test]
fn norm_gen_00038() {
    assert_eq!(normalize_plugin_name("Diva [x64]"), "diva");
}

#[test]
fn norm_gen_00039() {
    assert_eq!(normalize_plugin_name("Diva x64"), "diva");
}

#[test]
fn norm_gen_00040() {
    assert_eq!(normalize_plugin_name("Diva x86"), "diva");
}

#[test]
fn norm_gen_00041() {
    assert_eq!(normalize_plugin_name("Diva x86_64"), "diva");
}

#[test]
fn norm_gen_00042() {
    assert_eq!(normalize_plugin_name("EQ Eight"), "eq eight");
}

#[test]
fn norm_gen_00043() {
    assert_eq!(normalize_plugin_name("EQ Eight (AAX)"), "eq eight");
}

#[test]
fn norm_gen_00044() {
    assert_eq!(normalize_plugin_name("EQ Eight (ARM64)"), "eq eight");
}

#[test]
fn norm_gen_00045() {
    assert_eq!(normalize_plugin_name("EQ Eight (AU)"), "eq eight");
}

#[test]
fn norm_gen_00046() {
    assert_eq!(normalize_plugin_name("EQ Eight (Apple Silicon)"), "eq eight");
}

#[test]
fn norm_gen_00047() {
    assert_eq!(normalize_plugin_name("EQ Eight (Intel)"), "eq eight");
}

#[test]
fn norm_gen_00048() {
    assert_eq!(normalize_plugin_name("EQ Eight (Mono)"), "eq eight");
}

#[test]
fn norm_gen_00049() {
    assert_eq!(normalize_plugin_name("EQ Eight (Stereo)"), "eq eight");
}

#[test]
fn norm_gen_00050() {
    assert_eq!(normalize_plugin_name("EQ Eight (Universal)"), "eq eight");
}

#[test]
fn norm_gen_00051() {
    assert_eq!(normalize_plugin_name("EQ Eight (VST3)"), "eq eight");
}

#[test]
fn norm_gen_00052() {
    assert_eq!(normalize_plugin_name("EQ Eight (x64)"), "eq eight");
}

#[test]
fn norm_gen_00053() {
    assert_eq!(normalize_plugin_name("EQ Eight 32bit"), "eq eight");
}

#[test]
fn norm_gen_00054() {
    assert_eq!(normalize_plugin_name("EQ Eight 64bit"), "eq eight");
}

#[test]
fn norm_gen_00055() {
    assert_eq!(normalize_plugin_name("EQ Eight [x64]"), "eq eight");
}

#[test]
fn norm_gen_00056() {
    assert_eq!(normalize_plugin_name("EQ Eight x64"), "eq eight");
}

#[test]
fn norm_gen_00057() {
    assert_eq!(normalize_plugin_name("EQ Eight x86"), "eq eight");
}

#[test]
fn norm_gen_00058() {
    assert_eq!(normalize_plugin_name("EQ Eight x86_64"), "eq eight");
}

#[test]
fn norm_gen_00059() {
    assert_eq!(normalize_plugin_name("FabFilter"), "fabfilter");
}

#[test]
fn norm_gen_00060() {
    assert_eq!(normalize_plugin_name("FabFilter (AAX)"), "fabfilter");
}

#[test]
fn norm_gen_00061() {
    assert_eq!(normalize_plugin_name("FabFilter (ARM64)"), "fabfilter");
}

#[test]
fn norm_gen_00062() {
    assert_eq!(normalize_plugin_name("FabFilter (AU)"), "fabfilter");
}

#[test]
fn norm_gen_00063() {
    assert_eq!(normalize_plugin_name("FabFilter (Apple Silicon)"), "fabfilter");
}

#[test]
fn norm_gen_00064() {
    assert_eq!(normalize_plugin_name("FabFilter (Intel)"), "fabfilter");
}

#[test]
fn norm_gen_00065() {
    assert_eq!(normalize_plugin_name("FabFilter (Mono)"), "fabfilter");
}

#[test]
fn norm_gen_00066() {
    assert_eq!(normalize_plugin_name("FabFilter (Stereo)"), "fabfilter");
}

#[test]
fn norm_gen_00067() {
    assert_eq!(normalize_plugin_name("FabFilter (Universal)"), "fabfilter");
}

#[test]
fn norm_gen_00068() {
    assert_eq!(normalize_plugin_name("FabFilter (VST3)"), "fabfilter");
}

#[test]
fn norm_gen_00069() {
    assert_eq!(normalize_plugin_name("FabFilter (x64)"), "fabfilter");
}

#[test]
fn norm_gen_00070() {
    assert_eq!(normalize_plugin_name("FabFilter 32bit"), "fabfilter");
}

#[test]
fn norm_gen_00071() {
    assert_eq!(normalize_plugin_name("FabFilter 64bit"), "fabfilter");
}

#[test]
fn norm_gen_00072() {
    assert_eq!(normalize_plugin_name("FabFilter [x64]"), "fabfilter");
}

#[test]
fn norm_gen_00073() {
    assert_eq!(normalize_plugin_name("FabFilter x64"), "fabfilter");
}

#[test]
fn norm_gen_00074() {
    assert_eq!(normalize_plugin_name("FabFilter x86"), "fabfilter");
}

#[test]
fn norm_gen_00075() {
    assert_eq!(normalize_plugin_name("FabFilter x86_64"), "fabfilter");
}

#[test]
fn norm_gen_00076() {
    assert_eq!(normalize_plugin_name("Kontakt"), "kontakt");
}

#[test]
fn norm_gen_00077() {
    assert_eq!(normalize_plugin_name("Kontakt (AAX)"), "kontakt");
}

#[test]
fn norm_gen_00078() {
    assert_eq!(normalize_plugin_name("Kontakt (ARM64)"), "kontakt");
}

#[test]
fn norm_gen_00079() {
    assert_eq!(normalize_plugin_name("Kontakt (AU)"), "kontakt");
}

#[test]
fn norm_gen_00080() {
    assert_eq!(normalize_plugin_name("Kontakt (Apple Silicon)"), "kontakt");
}

#[test]
fn norm_gen_00081() {
    assert_eq!(normalize_plugin_name("Kontakt (Intel)"), "kontakt");
}

#[test]
fn norm_gen_00082() {
    assert_eq!(normalize_plugin_name("Kontakt (Mono)"), "kontakt");
}

#[test]
fn norm_gen_00083() {
    assert_eq!(normalize_plugin_name("Kontakt (Stereo)"), "kontakt");
}

#[test]
fn norm_gen_00084() {
    assert_eq!(normalize_plugin_name("Kontakt (Stereo) (x64)"), "kontakt");
}

#[test]
fn norm_gen_00085() {
    assert_eq!(normalize_plugin_name("Kontakt (Universal)"), "kontakt");
}

#[test]
fn norm_gen_00086() {
    assert_eq!(normalize_plugin_name("Kontakt (VST3)"), "kontakt");
}

#[test]
fn norm_gen_00087() {
    assert_eq!(normalize_plugin_name("Kontakt (x64)"), "kontakt");
}

#[test]
fn norm_gen_00088() {
    assert_eq!(normalize_plugin_name("Kontakt (x64) (VST3)"), "kontakt");
}

#[test]
fn norm_gen_00089() {
    assert_eq!(normalize_plugin_name("Kontakt 32bit"), "kontakt");
}

#[test]
fn norm_gen_00090() {
    assert_eq!(normalize_plugin_name("Kontakt 64bit"), "kontakt");
}

#[test]
fn norm_gen_00091() {
    assert_eq!(normalize_plugin_name("Kontakt [AU] (x64)"), "kontakt");
}

#[test]
fn norm_gen_00092() {
    assert_eq!(normalize_plugin_name("Kontakt [x64]"), "kontakt");
}

#[test]
fn norm_gen_00093() {
    assert_eq!(normalize_plugin_name("Kontakt x64"), "kontakt");
}

#[test]
fn norm_gen_00094() {
    assert_eq!(normalize_plugin_name("Kontakt x86"), "kontakt");
}

#[test]
fn norm_gen_00095() {
    assert_eq!(normalize_plugin_name("Kontakt x86_64"), "kontakt");
}

#[test]
fn norm_gen_00096() {
    assert_eq!(normalize_plugin_name("Legacy"), "legacy");
}

#[test]
fn norm_gen_00097() {
    assert_eq!(normalize_plugin_name("Legacy (AAX)"), "legacy");
}

#[test]
fn norm_gen_00098() {
    assert_eq!(normalize_plugin_name("Legacy (ARM64)"), "legacy");
}

#[test]
fn norm_gen_00099() {
    assert_eq!(normalize_plugin_name("Legacy (AU)"), "legacy");
}

#[test]
fn norm_gen_00100() {
    assert_eq!(normalize_plugin_name("Legacy (Apple Silicon)"), "legacy");
}

#[test]
fn norm_gen_00101() {
    assert_eq!(normalize_plugin_name("Legacy (Intel)"), "legacy");
}

#[test]
fn norm_gen_00102() {
    assert_eq!(normalize_plugin_name("Legacy (Mono)"), "legacy");
}

#[test]
fn norm_gen_00103() {
    assert_eq!(normalize_plugin_name("Legacy (Stereo)"), "legacy");
}

#[test]
fn norm_gen_00104() {
    assert_eq!(normalize_plugin_name("Legacy (Universal)"), "legacy");
}

#[test]
fn norm_gen_00105() {
    assert_eq!(normalize_plugin_name("Legacy (VST3)"), "legacy");
}

#[test]
fn norm_gen_00106() {
    assert_eq!(normalize_plugin_name("Legacy (x64)"), "legacy");
}

#[test]
fn norm_gen_00107() {
    assert_eq!(normalize_plugin_name("Legacy 32bit"), "legacy");
}

#[test]
fn norm_gen_00108() {
    assert_eq!(normalize_plugin_name("Legacy 64bit"), "legacy");
}

#[test]
fn norm_gen_00109() {
    assert_eq!(normalize_plugin_name("Legacy [x64]"), "legacy");
}

#[test]
fn norm_gen_00110() {
    assert_eq!(normalize_plugin_name("Legacy x64"), "legacy");
}

#[test]
fn norm_gen_00111() {
    assert_eq!(normalize_plugin_name("Legacy x86"), "legacy");
}

#[test]
fn norm_gen_00112() {
    assert_eq!(normalize_plugin_name("Legacy x86_64"), "legacy");
}

#[test]
fn norm_gen_00113() {
    assert_eq!(normalize_plugin_name("Massive"), "massive");
}

#[test]
fn norm_gen_00114() {
    assert_eq!(normalize_plugin_name("Massive (AAX)"), "massive");
}

#[test]
fn norm_gen_00115() {
    assert_eq!(normalize_plugin_name("Massive (ARM64)"), "massive");
}

#[test]
fn norm_gen_00116() {
    assert_eq!(normalize_plugin_name("Massive (AU)"), "massive");
}

#[test]
fn norm_gen_00117() {
    assert_eq!(normalize_plugin_name("Massive (Apple Silicon)"), "massive");
}

#[test]
fn norm_gen_00118() {
    assert_eq!(normalize_plugin_name("Massive (Intel)"), "massive");
}

#[test]
fn norm_gen_00119() {
    assert_eq!(normalize_plugin_name("Massive (Mono)"), "massive");
}

#[test]
fn norm_gen_00120() {
    assert_eq!(normalize_plugin_name("Massive (Stereo)"), "massive");
}

#[test]
fn norm_gen_00121() {
    assert_eq!(normalize_plugin_name("Massive (Universal)"), "massive");
}

#[test]
fn norm_gen_00122() {
    assert_eq!(normalize_plugin_name("Massive (VST3)"), "massive");
}

#[test]
fn norm_gen_00123() {
    assert_eq!(normalize_plugin_name("Massive (x64)"), "massive");
}

#[test]
fn norm_gen_00124() {
    assert_eq!(normalize_plugin_name("Massive 32bit"), "massive");
}

#[test]
fn norm_gen_00125() {
    assert_eq!(normalize_plugin_name("Massive 64bit"), "massive");
}

#[test]
fn norm_gen_00126() {
    assert_eq!(normalize_plugin_name("Massive [x64]"), "massive");
}

#[test]
fn norm_gen_00127() {
    assert_eq!(normalize_plugin_name("Massive x64"), "massive");
}

#[test]
fn norm_gen_00128() {
    assert_eq!(normalize_plugin_name("Massive x86"), "massive");
}

#[test]
fn norm_gen_00129() {
    assert_eq!(normalize_plugin_name("Massive x86_64"), "massive");
}

#[test]
fn norm_gen_00130() {
    assert_eq!(normalize_plugin_name("Omnisphere"), "omnisphere");
}

#[test]
fn norm_gen_00131() {
    assert_eq!(normalize_plugin_name("Omnisphere (AAX)"), "omnisphere");
}

#[test]
fn norm_gen_00132() {
    assert_eq!(normalize_plugin_name("Omnisphere (ARM64)"), "omnisphere");
}

#[test]
fn norm_gen_00133() {
    assert_eq!(normalize_plugin_name("Omnisphere (AU)"), "omnisphere");
}

#[test]
fn norm_gen_00134() {
    assert_eq!(normalize_plugin_name("Omnisphere (Apple Silicon)"), "omnisphere");
}

#[test]
fn norm_gen_00135() {
    assert_eq!(normalize_plugin_name("Omnisphere (Intel)"), "omnisphere");
}

#[test]
fn norm_gen_00136() {
    assert_eq!(normalize_plugin_name("Omnisphere (Mono)"), "omnisphere");
}

#[test]
fn norm_gen_00137() {
    assert_eq!(normalize_plugin_name("Omnisphere (Stereo)"), "omnisphere");
}

#[test]
fn norm_gen_00138() {
    assert_eq!(normalize_plugin_name("Omnisphere (Universal)"), "omnisphere");
}

#[test]
fn norm_gen_00139() {
    assert_eq!(normalize_plugin_name("Omnisphere (VST3)"), "omnisphere");
}

#[test]
fn norm_gen_00140() {
    assert_eq!(normalize_plugin_name("Omnisphere (x64)"), "omnisphere");
}

#[test]
fn norm_gen_00141() {
    assert_eq!(normalize_plugin_name("Omnisphere 32bit"), "omnisphere");
}

#[test]
fn norm_gen_00142() {
    assert_eq!(normalize_plugin_name("Omnisphere 64bit"), "omnisphere");
}

#[test]
fn norm_gen_00143() {
    assert_eq!(normalize_plugin_name("Omnisphere [x64]"), "omnisphere");
}

#[test]
fn norm_gen_00144() {
    assert_eq!(normalize_plugin_name("Omnisphere x64"), "omnisphere");
}

#[test]
fn norm_gen_00145() {
    assert_eq!(normalize_plugin_name("Omnisphere x86"), "omnisphere");
}

#[test]
fn norm_gen_00146() {
    assert_eq!(normalize_plugin_name("Omnisphere x86_64"), "omnisphere");
}

#[test]
fn norm_gen_00147() {
    assert_eq!(normalize_plugin_name("Pigments"), "pigments");
}

#[test]
fn norm_gen_00148() {
    assert_eq!(normalize_plugin_name("Pigments (AAX)"), "pigments");
}

#[test]
fn norm_gen_00149() {
    assert_eq!(normalize_plugin_name("Pigments (ARM64)"), "pigments");
}

#[test]
fn norm_gen_00150() {
    assert_eq!(normalize_plugin_name("Pigments (AU)"), "pigments");
}

#[test]
fn norm_gen_00151() {
    assert_eq!(normalize_plugin_name("Pigments (Apple Silicon)"), "pigments");
}

#[test]
fn norm_gen_00152() {
    assert_eq!(normalize_plugin_name("Pigments (Intel)"), "pigments");
}

#[test]
fn norm_gen_00153() {
    assert_eq!(normalize_plugin_name("Pigments (Mono)"), "pigments");
}

#[test]
fn norm_gen_00154() {
    assert_eq!(normalize_plugin_name("Pigments (Stereo)"), "pigments");
}

#[test]
fn norm_gen_00155() {
    assert_eq!(normalize_plugin_name("Pigments (Universal)"), "pigments");
}

#[test]
fn norm_gen_00156() {
    assert_eq!(normalize_plugin_name("Pigments (VST3)"), "pigments");
}

#[test]
fn norm_gen_00157() {
    assert_eq!(normalize_plugin_name("Pigments (x64)"), "pigments");
}

#[test]
fn norm_gen_00158() {
    assert_eq!(normalize_plugin_name("Pigments 32bit"), "pigments");
}

#[test]
fn norm_gen_00159() {
    assert_eq!(normalize_plugin_name("Pigments 64bit"), "pigments");
}

#[test]
fn norm_gen_00160() {
    assert_eq!(normalize_plugin_name("Pigments [x64]"), "pigments");
}

#[test]
fn norm_gen_00161() {
    assert_eq!(normalize_plugin_name("Pigments x64"), "pigments");
}

#[test]
fn norm_gen_00162() {
    assert_eq!(normalize_plugin_name("Pigments x86"), "pigments");
}

#[test]
fn norm_gen_00163() {
    assert_eq!(normalize_plugin_name("Pigments x86_64"), "pigments");
}

#[test]
fn norm_gen_00164() {
    assert_eq!(normalize_plugin_name("Pro   Q   3"), "pro q 3");
}

#[test]
fn norm_gen_00165() {
    assert_eq!(normalize_plugin_name("Pro-Q 3"), "pro-q 3");
}

#[test]
fn norm_gen_00166() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (AAX)"), "pro-q 3");
}

#[test]
fn norm_gen_00167() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (ARM64)"), "pro-q 3");
}

#[test]
fn norm_gen_00168() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (AU)"), "pro-q 3");
}

#[test]
fn norm_gen_00169() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (Apple Silicon)"), "pro-q 3");
}

#[test]
fn norm_gen_00170() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (Intel)"), "pro-q 3");
}

#[test]
fn norm_gen_00171() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (Mono)"), "pro-q 3");
}

#[test]
fn norm_gen_00172() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (Stereo)"), "pro-q 3");
}

#[test]
fn norm_gen_00173() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (Universal)"), "pro-q 3");
}

#[test]
fn norm_gen_00174() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (VST3)"), "pro-q 3");
}

#[test]
fn norm_gen_00175() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 (x64)"), "pro-q 3");
}

#[test]
fn norm_gen_00176() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 32bit"), "pro-q 3");
}

#[test]
fn norm_gen_00177() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 64bit"), "pro-q 3");
}

#[test]
fn norm_gen_00178() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 [x64]"), "pro-q 3");
}

#[test]
fn norm_gen_00179() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 x64"), "pro-q 3");
}

#[test]
fn norm_gen_00180() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 x86"), "pro-q 3");
}

#[test]
fn norm_gen_00181() {
    assert_eq!(normalize_plugin_name("Pro-Q 3 x86_64"), "pro-q 3");
}

#[test]
fn norm_gen_00182() {
    assert_eq!(normalize_plugin_name("Reaktor"), "reaktor");
}

#[test]
fn norm_gen_00183() {
    assert_eq!(normalize_plugin_name("Reaktor (AAX)"), "reaktor");
}

#[test]
fn norm_gen_00184() {
    assert_eq!(normalize_plugin_name("Reaktor (ARM64)"), "reaktor");
}

#[test]
fn norm_gen_00185() {
    assert_eq!(normalize_plugin_name("Reaktor (AU)"), "reaktor");
}

#[test]
fn norm_gen_00186() {
    assert_eq!(normalize_plugin_name("Reaktor (Apple Silicon)"), "reaktor");
}

#[test]
fn norm_gen_00187() {
    assert_eq!(normalize_plugin_name("Reaktor (Intel)"), "reaktor");
}

#[test]
fn norm_gen_00188() {
    assert_eq!(normalize_plugin_name("Reaktor (Mono)"), "reaktor");
}

#[test]
fn norm_gen_00189() {
    assert_eq!(normalize_plugin_name("Reaktor (Stereo)"), "reaktor");
}

#[test]
fn norm_gen_00190() {
    assert_eq!(normalize_plugin_name("Reaktor (Universal)"), "reaktor");
}

#[test]
fn norm_gen_00191() {
    assert_eq!(normalize_plugin_name("Reaktor (VST3)"), "reaktor");
}

#[test]
fn norm_gen_00192() {
    assert_eq!(normalize_plugin_name("Reaktor (x64)"), "reaktor");
}

#[test]
fn norm_gen_00193() {
    assert_eq!(normalize_plugin_name("Reaktor 32bit"), "reaktor");
}

#[test]
fn norm_gen_00194() {
    assert_eq!(normalize_plugin_name("Reaktor 64bit"), "reaktor");
}

#[test]
fn norm_gen_00195() {
    assert_eq!(normalize_plugin_name("Reaktor [x64]"), "reaktor");
}

#[test]
fn norm_gen_00196() {
    assert_eq!(normalize_plugin_name("Reaktor x64"), "reaktor");
}

#[test]
fn norm_gen_00197() {
    assert_eq!(normalize_plugin_name("Reaktor x86"), "reaktor");
}

#[test]
fn norm_gen_00198() {
    assert_eq!(normalize_plugin_name("Reaktor x86_64"), "reaktor");
}

#[test]
fn norm_gen_00199() {
    assert_eq!(normalize_plugin_name("Réverb"), "réverb");
}

#[test]
fn norm_gen_00200() {
    assert_eq!(normalize_plugin_name("Réverb (AAX)"), "réverb");
}

#[test]
fn norm_gen_00201() {
    assert_eq!(normalize_plugin_name("Réverb (ARM64)"), "réverb");
}

#[test]
fn norm_gen_00202() {
    assert_eq!(normalize_plugin_name("Réverb (AU)"), "réverb");
}

#[test]
fn norm_gen_00203() {
    assert_eq!(normalize_plugin_name("Réverb (Apple Silicon)"), "réverb");
}

#[test]
fn norm_gen_00204() {
    assert_eq!(normalize_plugin_name("Réverb (Intel)"), "réverb");
}

#[test]
fn norm_gen_00205() {
    assert_eq!(normalize_plugin_name("Réverb (Mono)"), "réverb");
}

#[test]
fn norm_gen_00206() {
    assert_eq!(normalize_plugin_name("Réverb (Stereo)"), "réverb");
}

#[test]
fn norm_gen_00207() {
    assert_eq!(normalize_plugin_name("Réverb (Universal)"), "réverb");
}

#[test]
fn norm_gen_00208() {
    assert_eq!(normalize_plugin_name("Réverb (VST3)"), "réverb");
}

#[test]
fn norm_gen_00209() {
    assert_eq!(normalize_plugin_name("Réverb (x64)"), "réverb");
}

#[test]
fn norm_gen_00210() {
    assert_eq!(normalize_plugin_name("Réverb 32bit"), "réverb");
}

#[test]
fn norm_gen_00211() {
    assert_eq!(normalize_plugin_name("Réverb 64bit"), "réverb");
}

#[test]
fn norm_gen_00212() {
    assert_eq!(normalize_plugin_name("Réverb [x64]"), "réverb");
}

#[test]
fn norm_gen_00213() {
    assert_eq!(normalize_plugin_name("Réverb x64"), "réverb");
}

#[test]
fn norm_gen_00214() {
    assert_eq!(normalize_plugin_name("Réverb x86"), "réverb");
}

#[test]
fn norm_gen_00215() {
    assert_eq!(normalize_plugin_name("Réverb x86_64"), "réverb");
}

#[test]
fn norm_gen_00216() {
    assert_eq!(normalize_plugin_name("Serum"), "serum");
}

#[test]
fn norm_gen_00217() {
    assert_eq!(normalize_plugin_name("Serum (AAX)"), "serum");
}

#[test]
fn norm_gen_00218() {
    assert_eq!(normalize_plugin_name("Serum (ARM64)"), "serum");
}

#[test]
fn norm_gen_00219() {
    assert_eq!(normalize_plugin_name("Serum (AU)"), "serum");
}

#[test]
fn norm_gen_00220() {
    assert_eq!(normalize_plugin_name("Serum (Apple Silicon)"), "serum");
}

#[test]
fn norm_gen_00221() {
    assert_eq!(normalize_plugin_name("Serum (Intel)"), "serum");
}

#[test]
fn norm_gen_00222() {
    assert_eq!(normalize_plugin_name("Serum (Mono)"), "serum");
}

#[test]
fn norm_gen_00223() {
    assert_eq!(normalize_plugin_name("Serum (Stereo)"), "serum");
}

#[test]
fn norm_gen_00224() {
    assert_eq!(normalize_plugin_name("Serum (Stereo) (x64)"), "serum");
}

#[test]
fn norm_gen_00225() {
    assert_eq!(normalize_plugin_name("Serum (Universal)"), "serum");
}

#[test]
fn norm_gen_00226() {
    assert_eq!(normalize_plugin_name("Serum (VST3)"), "serum");
}

#[test]
fn norm_gen_00227() {
    assert_eq!(normalize_plugin_name("Serum (x64)"), "serum");
}

#[test]
fn norm_gen_00228() {
    assert_eq!(normalize_plugin_name("Serum (x64) (VST3)"), "serum");
}

#[test]
fn norm_gen_00229() {
    assert_eq!(normalize_plugin_name("Serum 32bit"), "serum");
}

#[test]
fn norm_gen_00230() {
    assert_eq!(normalize_plugin_name("Serum 64bit"), "serum");
}

#[test]
fn norm_gen_00231() {
    assert_eq!(normalize_plugin_name("Serum [AU] (x64)"), "serum");
}

#[test]
fn norm_gen_00232() {
    assert_eq!(normalize_plugin_name("Serum [x64]"), "serum");
}

#[test]
fn norm_gen_00233() {
    assert_eq!(normalize_plugin_name("Serum x64"), "serum");
}

#[test]
fn norm_gen_00234() {
    assert_eq!(normalize_plugin_name("Serum x86"), "serum");
}

#[test]
fn norm_gen_00235() {
    assert_eq!(normalize_plugin_name("Serum x86_64"), "serum");
}

#[test]
fn norm_gen_00236() {
    assert_eq!(normalize_plugin_name("Synth1"), "synth1");
}

#[test]
fn norm_gen_00237() {
    assert_eq!(normalize_plugin_name("Synth1 (AAX)"), "synth1");
}

#[test]
fn norm_gen_00238() {
    assert_eq!(normalize_plugin_name("Synth1 (ARM64)"), "synth1");
}

#[test]
fn norm_gen_00239() {
    assert_eq!(normalize_plugin_name("Synth1 (AU)"), "synth1");
}

#[test]
fn norm_gen_00240() {
    assert_eq!(normalize_plugin_name("Synth1 (Apple Silicon)"), "synth1");
}

#[test]
fn norm_gen_00241() {
    assert_eq!(normalize_plugin_name("Synth1 (Intel)"), "synth1");
}

#[test]
fn norm_gen_00242() {
    assert_eq!(normalize_plugin_name("Synth1 (Mono)"), "synth1");
}

#[test]
fn norm_gen_00243() {
    assert_eq!(normalize_plugin_name("Synth1 (Stereo)"), "synth1");
}

#[test]
fn norm_gen_00244() {
    assert_eq!(normalize_plugin_name("Synth1 (Universal)"), "synth1");
}

#[test]
fn norm_gen_00245() {
    assert_eq!(normalize_plugin_name("Synth1 (VST3)"), "synth1");
}

#[test]
fn norm_gen_00246() {
    assert_eq!(normalize_plugin_name("Synth1 (x64)"), "synth1");
}

#[test]
fn norm_gen_00247() {
    assert_eq!(normalize_plugin_name("Synth1 32bit"), "synth1");
}

#[test]
fn norm_gen_00248() {
    assert_eq!(normalize_plugin_name("Synth1 64bit"), "synth1");
}

#[test]
fn norm_gen_00249() {
    assert_eq!(normalize_plugin_name("Synth1 [x64]"), "synth1");
}

#[test]
fn norm_gen_00250() {
    assert_eq!(normalize_plugin_name("Synth1 x64"), "synth1");
}

#[test]
fn norm_gen_00251() {
    assert_eq!(normalize_plugin_name("Synth1 x86"), "synth1");
}

#[test]
fn norm_gen_00252() {
    assert_eq!(normalize_plugin_name("Synth1 x86_64"), "synth1");
}

#[test]
fn norm_gen_00253() {
    assert_eq!(normalize_plugin_name("Tab\there"), "tab here");
}

#[test]
fn norm_gen_00254() {
    assert_eq!(normalize_plugin_name("Tune"), "tune");
}

#[test]
fn norm_gen_00255() {
    assert_eq!(normalize_plugin_name("Tune (AAX)"), "tune");
}

#[test]
fn norm_gen_00256() {
    assert_eq!(normalize_plugin_name("Tune (ARM64)"), "tune");
}

#[test]
fn norm_gen_00257() {
    assert_eq!(normalize_plugin_name("Tune (AU)"), "tune");
}

#[test]
fn norm_gen_00258() {
    assert_eq!(normalize_plugin_name("Tune (Apple Silicon)"), "tune");
}

#[test]
fn norm_gen_00259() {
    assert_eq!(normalize_plugin_name("Tune (Intel)"), "tune");
}

#[test]
fn norm_gen_00260() {
    assert_eq!(normalize_plugin_name("Tune (Mono)"), "tune");
}

#[test]
fn norm_gen_00261() {
    assert_eq!(normalize_plugin_name("Tune (Stereo)"), "tune");
}

#[test]
fn norm_gen_00262() {
    assert_eq!(normalize_plugin_name("Tune (Universal)"), "tune");
}

#[test]
fn norm_gen_00263() {
    assert_eq!(normalize_plugin_name("Tune (VST3)"), "tune");
}

#[test]
fn norm_gen_00264() {
    assert_eq!(normalize_plugin_name("Tune (x64)"), "tune");
}

#[test]
fn norm_gen_00265() {
    assert_eq!(normalize_plugin_name("Tune 32bit"), "tune");
}

#[test]
fn norm_gen_00266() {
    assert_eq!(normalize_plugin_name("Tune 64bit"), "tune");
}

#[test]
fn norm_gen_00267() {
    assert_eq!(normalize_plugin_name("Tune [x64]"), "tune");
}

#[test]
fn norm_gen_00268() {
    assert_eq!(normalize_plugin_name("Tune x64"), "tune");
}

#[test]
fn norm_gen_00269() {
    assert_eq!(normalize_plugin_name("Tune x86"), "tune");
}

#[test]
fn norm_gen_00270() {
    assert_eq!(normalize_plugin_name("Tune x86_64"), "tune");
}

#[test]
fn norm_gen_00271() {
    assert_eq!(normalize_plugin_name("Valhalla"), "valhalla");
}

#[test]
fn norm_gen_00272() {
    assert_eq!(normalize_plugin_name("Valhalla (AAX)"), "valhalla");
}

#[test]
fn norm_gen_00273() {
    assert_eq!(normalize_plugin_name("Valhalla (ARM64)"), "valhalla");
}

#[test]
fn norm_gen_00274() {
    assert_eq!(normalize_plugin_name("Valhalla (AU)"), "valhalla");
}

#[test]
fn norm_gen_00275() {
    assert_eq!(normalize_plugin_name("Valhalla (Apple Silicon)"), "valhalla");
}

#[test]
fn norm_gen_00276() {
    assert_eq!(normalize_plugin_name("Valhalla (Intel)"), "valhalla");
}

#[test]
fn norm_gen_00277() {
    assert_eq!(normalize_plugin_name("Valhalla (Mono)"), "valhalla");
}

#[test]
fn norm_gen_00278() {
    assert_eq!(normalize_plugin_name("Valhalla (Stereo)"), "valhalla");
}

#[test]
fn norm_gen_00279() {
    assert_eq!(normalize_plugin_name("Valhalla (Universal)"), "valhalla");
}

#[test]
fn norm_gen_00280() {
    assert_eq!(normalize_plugin_name("Valhalla (VST3)"), "valhalla");
}

#[test]
fn norm_gen_00281() {
    assert_eq!(normalize_plugin_name("Valhalla (x64)"), "valhalla");
}

#[test]
fn norm_gen_00282() {
    assert_eq!(normalize_plugin_name("Valhalla 32bit"), "valhalla");
}

#[test]
fn norm_gen_00283() {
    assert_eq!(normalize_plugin_name("Valhalla 64bit"), "valhalla");
}

#[test]
fn norm_gen_00284() {
    assert_eq!(normalize_plugin_name("Valhalla [x64]"), "valhalla");
}

#[test]
fn norm_gen_00285() {
    assert_eq!(normalize_plugin_name("Valhalla x64"), "valhalla");
}

#[test]
fn norm_gen_00286() {
    assert_eq!(normalize_plugin_name("Valhalla x86"), "valhalla");
}

#[test]
fn norm_gen_00287() {
    assert_eq!(normalize_plugin_name("Valhalla x86_64"), "valhalla");
}

#[test]
fn norm_gen_00288() {
    assert_eq!(normalize_plugin_name("插件A"), "插件a");
}

#[test]
fn norm_gen_00289() {
    assert_eq!(normalize_plugin_name("插件A (AAX)"), "插件a");
}

#[test]
fn norm_gen_00290() {
    assert_eq!(normalize_plugin_name("插件A (ARM64)"), "插件a");
}

#[test]
fn norm_gen_00291() {
    assert_eq!(normalize_plugin_name("插件A (AU)"), "插件a");
}

#[test]
fn norm_gen_00292() {
    assert_eq!(normalize_plugin_name("插件A (Apple Silicon)"), "插件a");
}

#[test]
fn norm_gen_00293() {
    assert_eq!(normalize_plugin_name("插件A (Intel)"), "插件a");
}

#[test]
fn norm_gen_00294() {
    assert_eq!(normalize_plugin_name("插件A (Mono)"), "插件a");
}

#[test]
fn norm_gen_00295() {
    assert_eq!(normalize_plugin_name("插件A (Stereo)"), "插件a");
}

#[test]
fn norm_gen_00296() {
    assert_eq!(normalize_plugin_name("插件A (Universal)"), "插件a");
}

#[test]
fn norm_gen_00297() {
    assert_eq!(normalize_plugin_name("插件A (VST3)"), "插件a");
}

#[test]
fn norm_gen_00298() {
    assert_eq!(normalize_plugin_name("插件A (x64)"), "插件a");
}

#[test]
fn norm_gen_00299() {
    assert_eq!(normalize_plugin_name("插件A 32bit"), "插件a");
}

#[test]
fn norm_gen_00300() {
    assert_eq!(normalize_plugin_name("插件A 64bit"), "插件a");
}

#[test]
fn norm_gen_00301() {
    assert_eq!(normalize_plugin_name("插件A [x64]"), "插件a");
}

#[test]
fn norm_gen_00302() {
    assert_eq!(normalize_plugin_name("插件A x64"), "插件a");
}

#[test]
fn norm_gen_00303() {
    assert_eq!(normalize_plugin_name("插件A x86"), "插件a");
}

#[test]
fn norm_gen_00304() {
    assert_eq!(normalize_plugin_name("插件A x86_64"), "插件a");
}

