//! Dev-only: print `#[test]` lines for `xref::normalize_plugin_name` (stdout → tests file).
//! Run: `cargo run --manifest-path src-tauri/Cargo.toml --example norm_gen`

fn main() {
    let mut inputs: Vec<String> = Vec::new();

    let bases = [
        "Serum",
        "Pro-Q 3",
        "Diva",
        "Massive",
        "Kontakt",
        "FabFilter",
        "Valhalla",
        "Omnisphere",
        "Pigments",
        "Reaktor",
        "Synth1",
        "EQ Eight",
        "Compressor",
        "Tune",
        "Legacy",
        "Réverb",
        "插件A",
    ];

    let suffixes = [
        "",
        "(x64)",
        "[x64]",
        "(VST3)",
        "(AU)",
        "(AAX)",
        "(ARM64)",
        "(Universal)",
        "(Stereo)",
        "(Mono)",
        "(Intel)",
        "(Apple Silicon)",
        "x64",
        "x86_64",
        "x86",
        "64bit",
        "32bit",
    ];

    for b in bases {
        for s in suffixes {
            if s.is_empty() {
                inputs.push(b.to_string());
            } else if s.starts_with('(') || s.starts_with('[') {
                inputs.push(format!("{b} {s}"));
            } else {
                inputs.push(format!("{b} {s}"));
            }
        }
    }

    // Nested arch strips
    for b in ["Serum", "Kontakt", "Diva"] {
        inputs.push(format!("{b} (x64) (VST3)"));
        inputs.push(format!("{b} (Stereo) (x64)"));
        inputs.push(format!("{b} [AU] (x64)"));
    }

    // Whitespace
    for s in ["  spaced  name  ", "Tab\there", "Pro   Q   3"] {
        inputs.push(s.to_string());
    }

    // Edge
    for s in ["", "   ", "(x64)", "(VST3)"] {
        inputs.push(s.to_string());
    }

    // Dedup
    inputs.sort();
    inputs.dedup();

    println!("//! Generated by `cargo run --example norm_gen` — do not hand-edit rows.");
    println!("use app_lib::xref::normalize_plugin_name;");
    println!();

    for (i, s) in inputs.iter().enumerate() {
        let exp = app_lib::xref::normalize_plugin_name(s);
        let lit = format!("{:?}", s);
        let exp_lit = format!("{:?}", exp);
        println!("#[test]");
        println!("fn norm_gen_{i:05}() {{");
        println!("    assert_eq!(normalize_plugin_name({lit}), {exp_lit});");
        println!("}}");
        println!();
    }
}
